## The IDs of all slope tiles.
enum SlopeTileID {
	SLOPE_TL = 100,
	SLOPE_CORNER_TL,
	SLOPE_BASE_TL,
	SLOPE_PEAK_TL,
	SLOPE_TR,
	SLOPE_CORNER_TR,
	SLOPE_BASE_TR,
	SLOPE_PEAK_TR,
	SLOPE_BL,
	SLOPE_CORNER_BL,
	SLOPE_BASE_BL,
	SLOPE_PEAK_BL,
	SLOPE_BR,
	SLOPE_CORNER_BR,
	SLOPE_BASE_BR,
	SLOPE_PEAK_BR,
	NONE
}
